import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  #"~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true

[bell]
animation = "EaseOutExpo"

[cursor]
unfocused_hollow = true

[font]
size = 12.0

[font.normal]
#family = "Meslo LG S for Powerline"
#style = "RegularForPowerline"
family = "MesloLGS Nerd Font"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["-l", "-c", "tmux -u attach || tmux -u"]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "buttonless"
#opacity = 0.95
option_as_alt = "None"

[window.dimensions]
columns = 140
lines = 38

[window.padding]
x = 10
y = 10
